#!/bin/sh
set -e

case "$1" in
    remove|purge)
        # Clean up udev
        if [ -x /usr/bin/udevadm ]; then
            udevadm control --reload-rules || true
        fi

        # Update Desktop Database
        if [ -x /usr/bin/update-desktop-database ]; then
            update-desktop-database -q || true
        fi
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
